
plugins {
    id 'java'

    alias(catalog.plugins.spotless) apply false
    alias(catalog.plugins.freefair.aspectj) apply false

    alias(catalog.plugins.spring.boot) apply false
    alias(catalog.plugins.spring.dependency.management) apply false
}

allprojects {
    group = 'com.gmail.bishoybasily.playground.weaving'
    version = '0.0.1-SNAPSHOT'
}


subprojects {
    apply plugin: 'java'
    apply plugin: 'conventions-spotless'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.named('test') {
        useJUnitPlatform()
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }
}
