pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    versionCatalogs {
        catalog {
            from(files("catalog.toml"))
        }
    }
}

rootProject.name = 'weaving-playground'

include 'app'
include 'app-dist'